# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLXUItRUrrJVlql1G9V1jaG_pStfeOKT
"""

# user_input.py

# Ask the user for their name and store it in a variable
name = input("Please enter your name: ")

# Ask the user for their age and store it in a variable
age = input("Please enter your age: ")

# Ask the user for their location and store it in a variable
location = input("Please enter your location: ")

# Print out a personalized message using the user's information
print(f"Hello {name}, you are {age} years old and live in {location}.")